name: Check code quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    name: Run biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
